### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by vpn1997** [gjdanis/2048#1]

**Comment by gjdanis** [comment]
Hey @vpn1997 thanks for checking this out!

I just ran ai.py from a python shell with:

```
>>> g = Game()
>>> aiplay(g)
...
```

The program is definitely slow, and the output could be improved up, but I was able to get to 2048 just fine (it's still going!). If you're in a hurry, try changing the depth in the search function to something less than 4, the default value. I'm going to close this issue unless you can give me more info about what's not working for you.

It's been awhile since I've touched this code and would love to see it improved upon. Here are a couple things I'm thinking would be good improvements:

- Add a CLI
- Make the search depth configurable
- Improve the output
- Add some simple stats that can be printed each time to justify the end move that was made

What do you think?

**Comment by vpn1997** [comment]
Hey srry for late reply. When i ran that program ,max i used to get was
256.Thats why i raised an issue.
Btw i used different heuristics and was able to generate tile upto 1024 all
the time and sometimes even 2048.
I made a github repo https://github.com/vpn1997/2048-Ai . Please do check
and if possible contribute or raise some issues:p.
thank you.
